secret:
  team-id: R7SQHMWJKU
  key-id: A76HA22K75
  client-id: 0d1a7d20dd3b49ce9b7fd34376126e57
  client-secret: 97defc4959814c9bb788574c4ff8d2aa
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVJrJRAoZI6S2UkwZA7EhHhKW5zSloouwue/Q3D4cyOmgCgYIKoZIzj0DAQehRANCAAQZyu0OBCN4XCY+4F/E0d+pqXJoLZ7hXbYSN4TMgiEjNnpeX0anKWMk8zeRmHfDa05waNKs5XAFQUyVr1X3PpvF
    -----END PRIVATE KEY-----
